var country_abbr = {
    "AFGHANISTAN": "AF",
    "ALBANIA": "AL",
    "ALGERIA": "DZ",
    "ANDORRA": "AD",  
    "ANGOLA": "AO",  
    "ANGUILLA": "AI",  
    "ANTARCTIC FISHERIES": "TF",  
    "ANTIGUA & BARBUDA": "AG",  
    "ARGENTINA": "AR",  
    "ARMENIA": "AM",  
    "ARUBA": "AW",  
    "AUSTRALIA": "AU",  
    "AUSTRIA": "AT",  
    "AZERBAIJAN": "AZ",  
    "BAHAMAS": "BS",  
    "BAHRAIN": "BH",  
    "BANGLADESH": "BD",  
    "BARBADOS": "BB",  
    "BELARUS": "BY",  
    "BELGIUM": "BE",  
    "BELIZE": "BZ", 
    "BENIN": "BJ",  
    "BERMUDA": "BM",  
    "BHUTAN": "BT",  
    "BONAIRE, SAINT EUSTATIUS, AND SABA": "BQ",  
    "BOSNIA & HERZEGOVINA": "BA",  
    "BOTSWANA": "BW",  
    "BRAZIL": "BR",  
    "BRITISH VIRGIN ISLANDS": "VG",  
    "BRUNEI (DARUSSALAM)": "BN",  
    "BULGARIA": "BG", 
    "BURKINA FASO": "BF",  
    "BURUNDI": "BI",  
    "CAMBODIA": "KH",  
    "CANADA": "CA",  
    "CAPE VERDE": "CV",  
    "CAYMAN ISLANDS": "KY",  
    "CENTRAL AFRICAN REPUBLIC": "CF",  
    "CHAD": "TD",  
    "CHILE": "CL", 
    "CHINA (MAINLAND)": "CN",  
    "CHRISTMAS ISLAND": "CX",  
    "COLOMBIA": "CO",  
    "COMOROS": "KM",  
    "CONGO": "CG",  
    "COOK ISLANDS": "CK",  
    "COSTA RICA": "CR",  
    "COTE D IVOIRE": "CI",  
    "CROATIA": "HR",  
    "CUBA": "CU",  
    "CURACAO": "CW",  
    "CYPRUS": "CY",  
    "CZECH REPUBLIC": "CZ",  
    "CZECHOSLOVAKIA": "CZ",
    "DEMOCRATIC PEOPLE S REPUBLIC OF KOREA": "KP",  
    "DEMOCRATIC REPUBLIC OF THE CONGO (FORMERLY ZAIRE)": "CD",  
    "DEMOCRATIC REPUBLIC OF VIETNAM": "VN",  
    "DENMARK": "DK",  
    "DJIBOUTI": "DJ",  
    "DOMINICA": "DM",  
    "DOMINICAN REPUBLIC": "DO",  
    "EAST & WEST PAKISTAN": "PK",  
    "ECUADOR": "EC",  
    "EGYPT": "EG",  
    "EL SALVADOR": "SV",  
    "EQUATORIAL GUINEA": "GQ",  
    "ERITREA": "ER", 
    "ESTONIA": "EE",  
    "ETHIOPIA": "ET", 
    "FAEROE ISLANDS": "FO",  
    "FALKLAND ISLANDS (MALVINAS)": "FK",  
    "FEDERAL REPUBLIC OF GERMANY": "DE",  
    "FEDERATED STATES OF MICRONESIA": "FM",  
    "FEDERATION OF MALAYA-SINGAPORE": "SG",  
    "FIJI": "FJ",  
    "FINLAND": "FI",  
    "FORMER DEMOCRATIC YEMEN": "YE",  
    "FORMER GERMAN DEMOCRATIC REPUBLIC": "DE",  
    "FORMER PANAMA CANAL ZONE": "PA",  
    "FORMER YEMEN": "YE",  
    "FRANCE (INCLUDING MONACO)": "FR",  
    "FRENCH EQUATORIAL AFRICA": "FR",  
    "FRENCH GUIANA": "GF",  
    "FRENCH INDO-CHINA": "FR", 
    "FRENCH POLYNESIA": "PF",  
    "FRENCH WEST AFRICA": "FR",  
    "GABON": "GA", 
    "GAMBIA": "GM",  
    "GEORGIA": "GE",  
    "GERMANY": "DE",  
    "GHANA": "GH",  
    "GIBRALTAR": "GI",  
    "GREECE": "GR",  
    "GREENLAND": "GL",  
    "GRENADA": "GD",  
    "GUADELOUPE": "GP",  
    "GUATEMALA": "GT",  
    "GUINEA": "GN", 
    "GUINEA BISSAU": "GW",  
    "GUYANA": "GY",
    "HAITI": "HT",  
    "HONDURAS": "HN",  
    "HONG KONG SPECIAL ADMINSTRATIVE REGION OF CHINA": "CN",  
    "HUNGARY": "HU",  
    "ICELAND": "IS",  
    "INDIA": "IN",  
    "INDONESIA": "ID",  
    "IRAQ": "IQ",  
    "IRELAND": "IE",  
    "ISLAMIC REPUBLIC OF IRAN": "IR",  
    "ISRAEL": "IL",  
    "ITALY (INCLUDING SAN MARINO)": "IT",  
    "JAMAICA": "JM",  
    "JAPAN": "JP",  
    "JAPAN (EXCLUDING THE RUYUKU ISLANDS)": "JP",  
    "JORDAN": "JO",  
    "KAZAKHSTAN": "KZ",  
    "KENYA": "KE",  
    "KIRIBATI": "KI",  
    "KUWAIT": "KW",  
    "KUWAITI OIL FIRES": "KW",  
    "KYRGYZSTAN": "KG",  
    "LAO PEOPLE S DEMOCRATIC REPUBLIC": "LA",  
    "LATVIA": "LV",  
    "LEBANON": "LB",  
    "LEEWARD ISLANDS": "",  
    "LESOTHO": "LS",  
    "LIBERIA": "LR",  
    "LIBYAN ARAB JAMAHIRIYAH": "LY",  
    "LIECHTENSTEIN": "LI",  
    "LITHUANIA": "LT",  
    "LUXEMBOURG": "LU",  
    "MACAU SPECIAL ADMINSTRATIVE REGION OF CHINA": "CN",  
    "MACEDONIA": "MK",  
    "MADAGASCAR": "MG",  
    "MALAWI": "MW",  
    "MALAYSIA": "MY",  
    "MALDIVES": "MV",  
    "MALI": "ML",  
    "MALTA": "MT",  
    "MARSHALL ISLANDS": "MH",  
    "MARTINIQUE": "MQ",  
    "MAURITANIA": "MR",  
    "MAURITIUS": "MU",  
    "MEXICO": "MX",  
    "MONGOLIA": "MN",  
    "MONTENEGRO": "ME",  
    "MONTSERRAT": "MS",  
    "MOROCCO": "MA",  
    "MOZAMBIQUE": "MZ",  
    "MYANMAR (FORMERLY BURMA)": "MM",  
    "NAMIBIA": "NA",  
    "NAURU": "NR",  
    "NEPAL": "NP",  
    "NETHERLAND ANTILLES": "NL",  
    "NETHERLAND ANTILLES AND ARUBA": "NL",  
    "NETHERLANDS": "NL",  
    "NEW CALEDONIA": "NC",
    "NEW ZEALAND": "NZ",  
    "NICARAGUA": "NI",  
    "NIGER": "NE",  
    "NIGERIA": "NG",  
    "NIUE": "NU",  
    "NORWAY": "NO",  
    "OCCUPIED PALESTINIAN TERRITORY": "PS",  
    "OMAN": "OM", 
    "PACIFIC ISLANDS (PALAU)": "PW",  
    "PAKISTAN": "PK",  
    "PALAU": "PW",  
    "PANAMA": "PA",  
    "PAPUA NEW GUINEA": "PG",  
    "PARAGUAY": "PY",  
    "PENINSULAR MALAYSIA": "MY",  
    "PERU": "PE",  
    "PHILIPPINES": "PH",  
    "PLURINATIONAL STATE OF BOLIVIA": "BO",  
    "POLAND": "PL", 
    "PORTUGAL": "PT",  
    "PUERTO RICO": "PR",  
    "QATAR": "QA",  
    "REPUBLIC OF CAMEROON": "CM",  
    "REPUBLIC OF KOREA": "KR",  
    "REPUBLIC OF MOLDOVA": "MD",  
    "REPUBLIC OF SOUTH SUDAN": "SS",  
    "REPUBLIC OF SOUTH VIETNAM": "VN",  
    "REPUBLIC OF SUDAN": "SD",  
    "REUNION": "RE",  
    "RHODESIA-NYASALAND": "GB",  
    "ROMANIA": "RO",  
    "RUSSIAN FEDERATION": "RU",  
    "RWANDA": "RW",  
    "RWANDA-URUNDI": "BE",  
    "RYUKYU ISLANDS": "JP",  
    "SABAH": "MY",  
    "SAINT HELENA": "SH",  
    "SAINT LUCIA": "LC",  
    "SAINT MARTIN (DUTCH PORTION)": "MF",  
    "SAMOA": "WS",  
    "SAO TOME & PRINCIPE": "ST",  
    "SARAWAK": "MY",  
    "SAUDI ARABIA": "SA",  
    "SENEGAL": "SN",  
    "SERBIA": "RS",  
    "SEYCHELLES": "SC",  
    "SIERRA LEONE": "SL",  
    "SINGAPORE": "SG",  
    "SLOVAKIA": "SK",  
    "SLOVENIA": "SI",  
    "SOLOMON ISLANDS": "SB",  
    "SOMALIA": "SO",  
    "SOUTH AFRICA": "ZA",  
    "SPAIN": "ES",  
    "SRI LANKA": "LK",  
    "ST. KITTS-NEVIS": "KN",  
    "ST. KITTS-NEVIS-ANGUILLA": "KN",  
    "ST. PIERRE & MIQUELON": "PM",  
    "ST. VINCENT & THE GRENADINES": "VC",  
    "SUDAN": "SD",  
    "SURINAME": "SR",  
    "SWAZILAND": "SZ",  
    "SWEDEN": "SE",  
    "SWITZERLAND": "CH",  
    "SYRIAN ARAB REPUBLIC": "SY",
    "TAIWAN": "TW",  
    "TAJIKISTAN": "TJ",  
    "TANGANYIKA": "TZ",  
    "THAILAND": "TH",  
    "TIMOR-LESTE (FORMERLY EAST TIMOR)": "TL",  
    "TOGO": "TG",  
    "TONGA": "TO",  
    "TRINIDAD AND TOBAGO": "TT",  
    "TUNISIA": "TN",  
    "TURKEY": "TR",  
    "TURKMENISTAN": "TM",  
    "TURKS AND CAICOS ISLANDS": "TC",  
    "TUVALU": "TV", 
    "UGANDA": "UG",  
    "UKRAINE": "UA",  
    "UNITED ARAB EMIRATES": "AE",  
    "UNITED KINGDOM": "GB",  
    "UNITED KOREA": "KR",  
    "UNITED REPUBLIC OF TANZANIA": "TZ",  
    "UNITED STATES OF AMERICA": "US",  
    "URUGUAY": "UY",  
    "USSR": "RU",  
    "UZBEKISTAN": "UZ",  
    "VANUATU": "VU",  
    "VENEZUELA": "VE",  
    "VIET NAM": "VN",  
    "WALLIS AND FUTUNA ISLANDS": "FR",  
    "YEMEN": "YE",  
    "YUGOSLAVIA (FORMER SOCIALIST FEDERAL REPUBLIC)": "",  
    "YUGOSLAVIA (MONTENEGRO & SERBIA)": "ME",  
    "ZAMBIA": "ZM",  
    "ZANZIBAR": "TZ",  
    "ZIMBABWE" :"ZW"
}

/** returns an array with list of countries from dataset
function getCountries(data) {
    var countries = [];
    for(i in data) countries.push(data[i].Country);
    countries = Array.from(new Set(countries));       // remove duplicates
    return countries;
}
**/